// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://secukjigipduggbgxswk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlY3VramlnaXBkdWdnYmd4c3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyODk2NjcsImV4cCI6MjA1Njg2NTY2N30.X8BEswT4wYv5octJgyzX3Eytn0UCjpBNCY7W7nakOTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);